name: notepadd
description: Une application de notes in-croy-able

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  intl: ^0.17.0
  collection: ^1.15.0

  provider: ^6.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_quill: ^7.1.19
  table_calendar: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  hive_generator: ^1.1.1
  build_runner: ^2.1.4

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true